all:
  vars:
    ansible_ssh_user: matheus
    harbor_admin: cncfdemo
    cert_domain_name: registry.cncf.raj.ninja
    cert_admin_email: matheus@nanoshots.com.br
  children:
    kubernetes:
      children: 
        masters:
          vars:
            linkerd_url: linkerd.raj.ninja
          hosts:
            35.224.41.89:
        nodes:
          hosts:
            104.154.132.181:
            34.67.154.18:
            35.232.137.196:
    harbor:
      hosts:
        34.71.192.242

    front-proxy:
      hosts:
        104.155.154.113
