- name: Create token to join cluster
  shell: kubeadm token create --print-join-command
  register: join_command_raw
- debug: msg="join command is {{ join_command_raw.stdout }}"

- name: Set join command as fact
  set_fact: join_command="{{ join_command_raw.stdout }}"